FROM registry.cn-zhangjiakou.aliyuncs.com/atguigu-practice/base-centos
RUN curl -L https://dlcdn.apache.org/zookeeper/zookeeper-3.7.1/apache-zookeeper-3.7.1-bin.tar.gz | tar -zxC /opt/module
COPY env.sh /etc/profile.d/linux-practice-02.sh
