name: Data Warehouse
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Practice
    types:
      - completed
  push:
    branches: [ master ]
    paths:
      - datawarehouse/**
      - .github/workflows/datawarehouse.yaml

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: atguigu-datawarehouse
  IMAGE: datawarehouse

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Detect Date
        run: echo "VERSION=$(date +%F)" >>$GITHUB_ENV
      - name: Build Image
        run: |
          TAG=${VERSION}
          docker login \
            --username="${{ secrets.DOCKER_USERNAME }}" \
            --password="${{ secrets.DOCKER_PASSWORD }}" \
            ${REGISTRY}
          cd ${IMAGE}
          docker build . --file Dockerfile \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG} \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest