name: Hadoop Practice 04
on:
  workflow_call:
  push:
    branches: [ master ]
    paths:
      - hadoop-practice-04/**

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: atguigu-practice
  IMAGE: hadoop-practice-04

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Detect Date
        run: echo "VERSION=$(date +%F)" >>$GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ env.IMAGE }}
          pull: true
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
