name: Trigger All
on:
  workflow_dispatch:

jobs:
  base-centos:
    uses: ./.github/workflows/base-centos.yaml
    secrets: inherit
  java:
    needs: base-centos
    uses: ./.github/workflows/java.yaml
    secrets: inherit
  zookeeper:
    needs: java
    uses: ./.github/workflows/zookeeper.yaml
    secrets: inherit
  hadoop:
    needs: zookeeper
    uses: ./.github/workflows/hadoop.yaml
    secrets: inherit
