name: Trigger All
on:
  workflow_dispatch:

jobs:
  base-centos:
    uses: ./.github/workflows/base-centos.yaml
    secrets: inherit
  java:
    needs: base-centos
    uses: ./.github/workflows/java.yaml
    secrets: inherit
  zookeeper:
    needs: java
    uses: ./.github/workflows/zookeeper.yaml
    secrets: inherit
  hadoop:
    needs: zookeeper
    uses: ./.github/workflows/hadoop.yaml
    secrets: inherit
  hive:
    needs: hadoop
    uses: ./.github/workflows/hive.yaml
    secrets: inherit
  flume:
    needs: hive
    uses: ./.github/workflows/flume.yaml
    secrets: inherit
  kafka:
    needs: flume
    uses: ./.github/workflows/kafka.yaml
    secrets: inherit
  datawarehouse:
    needs: kafka
    uses: ./.github/workflows/datawarehouse.yaml
    secrets: inherit
  hadoop-practice-01:
    needs: hadoop
    uses: ./.github/workflows/hadoop-practice-01.yaml
    secrets: inherit
  hadoop-practice-02:
    needs: hadoop
    uses: ./.github/workflows/hadoop-practice-02.yaml
    secrets: inherit
  hadoop-practice-03:
    needs: hadoop
    uses: ./.github/workflows/hadoop-practice-03.yaml
    secrets: inherit
  hadoop-practice-04:
    needs: hadoop
    uses: ./.github/workflows/hadoop-practice-04.yaml
    secrets: inherit
  hadoop-practice-05:
    needs: hadoop
    uses: ./.github/workflows/hadoop-practice-05.yaml
    secrets: inherit
  linux-practice-01:
    needs: datawarehouse
    uses: ./.github/workflows/linux-practice-01.yaml
    secrets: inherit
  hadoop-practice-06:
    needs: hadoop
    uses: ./.github/workflows/hadoop-practice-06.yaml
    secrets: inherit
  linux-practice-02:
    needs: base-centos
    uses: ./.github/workflows/linux-practice-02.yaml
    secrets: inherit
  flume-practice-01:
    needs: flume
    uses: ./.github/workflows/flume-practice-01.yaml
    secrets: inherit
  flume-practice-02:
    needs: flume
    uses: ./.github/workflows/flume-practice-02.yaml
    secrets: inherit
