name: Trigger All
on:
  workflow_dispatch:

jobs:
  base-centos:
    uses: ./.github/workflows/base-centos.yaml
    secrets: inherit
  java:
    needs: base-centos
    uses: ./.github/workflows/java.yaml
    secrets: inherit
  zookeeper:
    needs: java
    uses: ./.github/workflows/zookeeper.yaml
    secrets: inherit
  hadoop:
    needs: zookeeper
    uses: ./.github/workflows/hadoop.yaml
    secrets: inherit
  hive:
    needs: hadoop
    uses: ./.github/workflows/hive.yaml
    secrets: inherit
  flume:
    needs: hive
    uses: ./.github/workflows/flume.yaml
    secrets: inherit
  kafka:
    needs: flume
    uses: ./.github/workflows/kafka.yaml
    secrets: inherit
  datawarehouse:
    needs: kafka
    uses: ./.github/workflows/datawarehouse.yaml
    secrets: inherit
